Repository Gerencia-de-configuracao-e-mudancas/projeto-final-manuwillfinal, pull requests merged in 2025-03, with the labels that each got.

#10 feat: função para criar personagem
  creation.js
  zAnotacoes.txt
Labels: enhancement

#11 criação de manual
  handbook.css
  handbook.html
Labels: enhancement

#13 feat: rolagem de dado e ajustes na interface
  cores.css
  creation.css
  creation.html
  creation.js
  index.css
  index.html
  script.js
Labels: enhancement

#15 fix: correções na rolagem de dados
  index.js
Labels: bug, enhancement

#17 Update README.md
  README.md
Labels: enhancement

#19 Update README.md
  README.md
Labels: documentation
